apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: argocd
    repoURL: https://github.com/leoluz/argocd
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
