apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook2
  namespace: argocd
  labels:
    app-team: platform
    name: guestbook2
    app-bu: devx
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: kustomize-guestbook
    plugin:
      env:
        - name: FOO
          value: luz

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook

  # Sync policy
  syncPolicy: {}
