apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: big-crd
  namespace: argocd
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    repoURL: file:///Users/lalmeida1/dev/git/kube-tests
    targetRevision: HEAD
    path: argocd/big-crd

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=false
