apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-log-metrics
  namespace: {{ .Values.namespace }}

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-log-metrics
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-log-metrics 
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: kube-log-metrics 
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: kube-log-metrics 
  apiGroup: rbac.authorization.k8s.io

---

kind: Service
apiVersion: v1
metadata:
  name: kube-log-metrics
  namespace: {{ .Values.namespace }}
  labels:
    ad-app: kube-log-metrics
  annotations:
    appdirect.com/deploy.canary: "false"
    appdirect.com/metadata.owner: platformdev@appdirect.com
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
spec:
  selector:
    ad-app: kube-log-metrics
  ports:
  - name: http
    port: 80
    targetPort: http-port

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kube-log-metrics
  namespace: {{ .Values.namespace }}
  labels:
    ad-app: kube-log-metrics
  annotations:
    appdirect.com/deploy.canary: "false"
    appdirect.com/metadata.github: https://github.com/AppDirect/kube-log-metrics
    appdirect.com/metadata.owner: platformdev@appdirect.com
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  revisionHistoryLimit: 5
  replicas: 1
  selector:
    matchLabels:
      ad-app: kube-log-metrics 
  progressDeadlineSeconds: 120
  template:
    metadata:
      labels:
        ad-app: kube-log-metrics
    spec:
      serviceAccountName: kube-log-metrics
      containers:
      - name: kube-log-metrics
        image: {{ .Values.image.repo }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: Always 
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 10000
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 2000m
            memory: 256Mi
        env:
        - name: APP_LOG_LEVEL
          value: "INFO"
        - name: APP_LOGS_LIMIT_BYTES
          value: "5000000"
        - name: APP_LOGS_POOLING_SECONDS
          value: "60"
        - name: APP_HTTP_PORT
          value: "8080"
        - name: APP_ERROR_REGEX
          value: "(error|ERROR|Exception)"
        - name: APP_EXPORT_LABELS
          value: "ad-app"
        - name: APP_CANARY_ANNOTATION
          value: "appdirect.com/deploy.canary"
        ports:
        - containerPort: 8080
          name: http-port
        livenessProbe:
          httpGet:
            path: /metrics
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 20
        readinessProbe:
          httpGet:
            path: /metrics
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 30
