apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cddemo
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  source:
    path: apps/cddemo
    repoURL: https://github.com/leoluz/argocd
    targetRevision: {{ .Values.spec.source.targetRevision }}
{{- if .Values.autoSync }}
  syncPolicy:
    automated:
      prune: true
{{- end }}
