apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

patchesStrategicMerge:
- cmp-sidecar-patch.yaml

resources:
- github.com/argoproj/argo-cd/manifests/cluster-install
- configmap.yaml
